[package]
name = "mkw-tracker"
version = "3.0.6"
edition = "2021"

[lib]
name = "mkw_tracker_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-shell = "2"
tauri-plugin-process = "2"
tauri-plugin-log = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-autostart = "2"
image = { version = "0.25", default-features = false, features = ["png"] }
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
discord-rich-presence = "1.1"
reqwest = { version = "0.12", features = ["json", "blocking"] }
rusqlite = { version = "0.32", features = ["bundled"] }
velopack = "1.2.0"
sha2 = "0.10"
tar = "0.4"
fs2 = "0.4"

[target.'cfg(target_os = "windows")'.dependencies]
webview2-com = "0.38"
