"""
Camera source abstraction supporting HDR (ffmpeg pipe) and SDR (cv2.VideoCapture).

Auto-detection logic (build_camera_source):
  1. Query DirectShow devices for P010 (10-bit HDR) capability via ffmpeg.
  2. If found → FfmpegCameraSource: ffmpeg captures P010, converts to bgr24 in
     the ffmpeg process, pipes raw bytes to Python.  Resolution and framerate are
     probed from the device via ffprobe before starting the pipe; .read() blocks
     until the next frame arrives, matching the cv2.VideoCapture.read() contract.
  3. Otherwise → VideoCaptureSource: thin cv2.VideoCapture wrapper (SDR path,
     used for OBS Virtual Camera and other SDR sources). Resolution is read back
     from the device after open - never forced.

Why bgr24 via ffmpeg rather than keeping P010 in Python:
  - Templates are generated by the program itself from the same frames it
    captures, so the absolute pixel values don't matter - only consistency.
  - ffmpeg's BT.2020 → bgr24 conversion is stable frame-to-frame; the Elgato
    driver's internal HDR→SDR conversion is not, causing minimap circle tracking
    to fail on HDR content.
  - All existing OpenCV code (template matching, Hough, HSV) works unchanged
    because frames arrive as standard uint8 BGR.
"""

import ctypes
import ctypes.wintypes
import msvcrt
import os
import subprocess
import sys
import threading
from typing import Optional, Tuple

import cv2
import numpy as np


# ── Internal helpers ──────────────────────────────────────────────────────────

def _bundled_bin(name: str) -> str:
    """Return the path to a bundled binary (ffmpeg/ffprobe) when frozen,
    or just the bare name (resolved via PATH) in development."""
    if getattr(sys, 'frozen', False):
        candidate = os.path.join(sys._MEIPASS, name + '.exe')
        if os.path.isfile(candidate):
            return candidate
    return name


def _run(*args, **kwargs):
    return subprocess.run(*args, capture_output=True, text=True, **kwargs)


# Windows PeekNamedPipe: returns how many bytes are immediately available in
# the OS pipe buffer without consuming them.  Used to detect frame backlog.
_kernel32 = ctypes.windll.kernel32
_kernel32.PeekNamedPipe.argtypes = [
    ctypes.wintypes.HANDLE,
    ctypes.c_void_p, ctypes.wintypes.DWORD, ctypes.c_void_p,
    ctypes.POINTER(ctypes.wintypes.DWORD),
    ctypes.c_void_p,
]
_kernel32.PeekNamedPipe.restype = ctypes.wintypes.BOOL


def _available_bytes(win_handle: int) -> int:
    avail = ctypes.wintypes.DWORD(0)
    _kernel32.PeekNamedPipe(win_handle, None, 0, None, ctypes.byref(avail), None)
    return avail.value


def _fill_frame(raw_io, mv: memoryview, n: int) -> bool:
    """Fill memoryview mv[:n] from raw (unbuffered) FileIO. Returns False on EOF."""
    total = 0
    while total < n:
        got = raw_io.readinto(mv[total:])
        if not got:
            return False
        total += got
    return True


# ── Device discovery ──────────────────────────────────────────────────────────

def list_dshow_video_devices() -> list[str]:
    """Return friendly names of all DirectShow video devices via ffmpeg."""
    r = _run([_bundled_bin("ffmpeg"), "-f", "dshow", "-list_devices", "true", "-i", "dummy"])
    names = []
    for line in r.stderr.splitlines():
        if "(video)" in line and '"' in line:
            names.append(line.split('"')[1])
    return names


def _device_has_p010(device_name: str) -> bool:
    """Return True if the device advertises the P010 FourCC (10-bit HDR) via dshow."""
    r = _run([_bundled_bin("ffmpeg"), "-f", "dshow", "-list_options", "true",
              "-i", f"video={device_name}"])
    return "0x30313050" in r.stderr   # P010 little-endian FourCC


def _find_p010_device() -> Optional[str]:
    """Return the first DirectShow device that advertises P010, or None."""
    for name in list_dshow_video_devices():
        if _device_has_p010(name):
            return name
    return None


def _find_obs_device() -> tuple[int, str]:
    """Return (index, name) for OBS Virtual Camera, or (0, '')."""
    for index, name in enumerate(list_dshow_video_devices()):
        if "obs" in name.lower():
            print(f"[Camera] OBS Virtual Camera at index {index}: {name!r}")
            return index, name
    return 0, ""


_MAX_FPS = 60   # cap all sources to this; Windows camera sharing can inflate fps arbitrarily


def _probe_device_size(device_name: str) -> tuple[int, int, int]:
    """
    Query the device's current output resolution and framerate via ffprobe.
    Falls back to 1920×1080@60 if the probe times out or fails.
    The reported fps is capped at _MAX_FPS regardless of what the device advertises.
    """
    import json as _json
    try:
        r = subprocess.run(
            [_bundled_bin("ffprobe"), "-v", "quiet", "-f", "dshow",
             "-i", f"video={device_name}",
             "-show_streams", "-select_streams", "v:0",
             "-of", "json"],
            capture_output=True, text=True, timeout=8,
        )
        streams = _json.loads(r.stdout).get("streams", [])
        if not streams:
            raise ValueError("no video streams")
        s = streams[0]
        w = int(s["width"])
        h = int(s["height"])
        num, den = (s.get("r_frame_rate") or "60/1").split("/")
        fps_raw = max(1, round(float(num) / max(1, float(den))))
        fps = min(fps_raw, _MAX_FPS)
        if fps_raw != fps:
            print(f"[Camera] probe: {device_name!r} -> {w}x{h} @ {fps_raw}fps (capped to {fps}fps)")
        else:
            print(f"[Camera] probe: {device_name!r} -> {w}x{h} @ {fps}fps")
        return w, h, fps
    except Exception as e:
        print(f"[Camera] probe failed ({e}), defaulting to 1920x1080@60")
        return 1920, 1080, 60


# ── Source classes ────────────────────────────────────────────────────────────

class FfmpegCameraSource:
    """
    HDR camera source: ffmpeg dshow → bgr24 pipe.

    Replicates cv2.VideoCapture's "always return the latest frame" behaviour:
    a daemon reader thread fills frames via raw (unbuffered) FileIO, then uses
    PeekNamedPipe to detect any queued backlog and drains it by overwriting the
    same buffer - only the newest frame is ever delivered to the main loop.

    Three pre-allocated numpy buffers rotate in a ring so the reader and main
    loop always work on different memory with no per-frame allocation.
    """

    def __init__(self, device_name: str) -> None:
        width, height, fps = _probe_device_size(device_name)
        self.width  = width
        self.height = height
        self.fps    = fps
        self._n = width * height * 3  # bytes per bgr24 frame
        self._pending_key = -1        # key press captured while waiting for a frame

        # Triple-buffer ring: reader writes to bufs[_wi]; .read() returns
        # bufs[(_wi + 2) % 3] (the frame written just before the current one).
        # With three slots the reader is always at least one buffer ahead of
        # the main loop, so they never share memory.
        self._bufs = [np.empty((height, width, 3), dtype=np.uint8)
                      for _ in range(3)]
        self._wi        = 0
        self._lock      = threading.Lock()
        self._new_frame = threading.Event()
        self._running   = True

        # Pre-allocated drain buffer: holds up to 16 frames for batch skipping.
        # A single large readinto drains all queued frames in one OS call instead
        # of one readinto-loop per frame, cutting drain time from O(frames × 15ms)
        # to ~1–2ms regardless of backlog size.
        _DRAIN_FRAMES   = 16
        self._drain_buf = np.empty(self._n * _DRAIN_FRAMES, dtype=np.uint8)
        self._drain_mv  = memoryview(self._drain_buf)

        cmd = [
            _bundled_bin("ffmpeg"),
            "-fflags",            "nobuffer",
            "-flags",             "low_delay",
            "-loglevel",          "error",
            "-f", "dshow",
            "-rtbufsize",         "16M",   # ~4 P010 frames; 1M was sub-frame, causing drops
            "-thread_queue_size", "1",     # restrict ffmpeg's input thread queue to 1 packet
            "-i", f"video={device_name}",
            "-f", "rawvideo", "-pix_fmt", "bgr24",
            "-s", f"{width}x{height}",    # scale output to probed size for consistent buffer layout
            "-r", str(_MAX_FPS),          # hard cap output rate; Windows sharing can inflate device fps
            "pipe:1",
        ]
        self.device_name = device_name
        self._proc = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
        )
        self._thread = threading.Thread(
            target=self._reader, daemon=True, name="CameraReader",
        )
        self._thread.start()
        print(f"[Camera] ffmpeg HDR pipe: {device_name!r} "
              f"{width}x{height} @ {fps}fps (bgr24)")

    def _reader(self) -> None:
        import time as _time
        raw    = self._proc.stdout.raw          # unbuffered FileIO - no internal copy
        handle = msvcrt.get_osfhandle(raw.fileno())
        n      = self._n

        _diag_t     = _time.monotonic()
        _diag_total = 0      # frames delivered to ring
        _diag_drain = 0      # frames discarded in drain
        _DIAG_INTERVAL = 5.0

        while self._running:
            wb = self._bufs[self._wi]
            mv = memoryview(wb.ravel())

            # Fill one complete frame directly into the pre-allocated buffer.
            t0 = _time.monotonic()
            if not _fill_frame(raw, mv, n):
                self._running = False
                break
            fill_ms = (_time.monotonic() - t0) * 1000

            # Drain any backlogged frames in one large batch read.
            # Reading all queued bytes in a single readinto call is ~10× faster
            # than draining one frame at a time; the OS hands back all buffered
            # data in one shot since it's already in kernel memory.
            avail = _available_bytes(handle)
            drained = 0
            if avail >= n:
                drain_mv = self._drain_mv
                to_read  = min((avail // n) * n, len(drain_mv))
                total    = 0
                while total < to_read:
                    got = raw.readinto(drain_mv[total:to_read])
                    if not got:
                        self._running = False
                        return
                    total += got
                complete = total // n
                if complete > 0:
                    last = (complete - 1) * n
                    mv[:] = drain_mv[last : last + n]
                    drained = complete

            # Advance the ring and signal the main loop.
            with self._lock:
                self._wi = (self._wi + 1) % 3
            self._new_frame.set()

            _diag_total += 1
            _diag_drain += drained

            now = _time.monotonic()
            if now - _diag_t >= _DIAG_INTERVAL:
                elapsed = now - _diag_t
                fps_in  = (_diag_total + _diag_drain) / elapsed
                fps_out = _diag_total / elapsed
                print(
                    f"[Camera] reader: fill={fill_ms:.1f}ms  "
                    f"in={fps_in:.1f}fps  out={fps_out:.1f}fps  "
                    f"drain={_diag_drain} frames in {elapsed:.0f}s  "
                    f"pipe_avail={avail/n:.1f}fr"
                )
                _diag_t     = now
                _diag_total = 0
                _diag_drain = 0

    def read(self) -> Tuple[bool, Optional[np.ndarray]]:
        # Wait for the next frame while keeping the Windows message pump alive.
        #
        # cv2.waitKey(1) was the original approach but is the wrong tool here:
        # it's designed to be called once after imshow, not 16× per frame.
        # More importantly, it sleeps via the Windows timer which defaults to
        # 15.6ms resolution - making every "1ms" wait wildly variable.
        #
        # Instead: cv2.pollKey() processes all pending messages immediately
        # (non-blocking), then Event.wait(0.001) sleeps precisely 1ms thanks
        # to timeBeginPeriod(1) set in main.py. This gives the same message-pump
        # coverage as waitKey while being far more predictable.
        import time as _time
        deadline = _time.monotonic() + 5.0
        while True:
            k = cv2.pollKey()   # non-blocking: flush Windows message queue now
            if k != -1:
                self._pending_key = k
            if self._new_frame.wait(0.001):   # sleeps ≤1ms; precise with timeBeginPeriod(1)
                break
            if _time.monotonic() > deadline:
                return False, None
        self._new_frame.clear()
        with self._lock:
            # The slot written two steps ago is safe: the reader is now one
            # full slot ahead, and the main loop processes in under a frame period.
            return True, self._bufs[(self._wi + 2) % 3]

    def waitKey(self, delay: int = 1) -> int:
        """Return any key press captured during read(), then fall back to cv2.waitKey()."""
        k = self._pending_key
        self._pending_key = -1
        if k != -1:
            return k
        return cv2.waitKey(delay)

    def release(self) -> None:
        self._running = False
        self._proc.terminate()
        try:
            self._proc.wait(timeout=3.0)
        except subprocess.TimeoutExpired:
            self._proc.kill()


class VideoCaptureSource:
    """SDR camera source: thin wrapper around cv2.VideoCapture (dshow backend)."""

    def __init__(self, index: int, device_name: str = "") -> None:
        self._cap = cv2.VideoCapture(index, cv2.CAP_DSHOW)
        self._cap.set(cv2.CAP_PROP_FPS, _MAX_FPS)
        # Read back what the device actually delivers - don't force a resolution.
        self.width       = int(self._cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        self.height      = int(self._cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        self.fps         = min(self._cap.get(cv2.CAP_PROP_FPS), _MAX_FPS)
        self.device_name = device_name or f"index:{index}"
        print(f"[Camera] DSHOW SDR: {self.device_name!r} "
              f"{self.width}x{self.height} @ {self.fps}fps")

    def read(self) -> Tuple[bool, Optional[np.ndarray]]:
        return self._cap.read()

    def waitKey(self, delay: int = 1) -> int:
        return cv2.waitKey(delay)

    def release(self) -> None:
        self._cap.release()


class VideoFileSource:
    """Dev/test source: play a video file in place of a capture device.

    Conforms to the same interface as the live sources (read/waitKey/release +
    width/height/fps/device_name), so the main loop is unchanged.  Frames are
    returned at the file's native resolution; main._norm() resizes them to
    1920x1080 like any other source.

    Playback tracks wall-clock time (real time): the frame returned is chosen
    from elapsed_time x fps, and any frames we're too slow to decode are dropped
    via grab() - exactly like a live capture card always handing back its newest
    frame.  This keeps the video at true speed regardless of its fps or how heavy
    per-frame processing is, and the wall-clock tracker rate limits (10Hz scans,
    timestamp bursts, EMA) behave as they do live.  Loops at EOF unless loop=False.

    target_fps:  None -> play at the file's own fps (true real time).
                 >0   -> play at this fps instead (e.g. 30 -> half-speed slow-mo).
                 0    -> no pacing and no dropping: decode every frame as fast as
                         possible (offline batch analysis).
    """

    def __init__(self, path: str, loop: bool = True,
                 target_fps: Optional[float] = None) -> None:
        if not os.path.isfile(path):
            raise RuntimeError(f"Video file not found: {path}")
        self._cap = cv2.VideoCapture(path)
        if not self._cap.isOpened():
            raise RuntimeError(f"Could not open video file: {path}")
        self.width   = int(self._cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        self.height  = int(self._cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        file_fps     = self._cap.get(cv2.CAP_PROP_FPS) or float(_MAX_FPS)
        # Playback clock.  None -> the file's own fps (true real time); a given
        # value overrides it; 0 disables pacing entirely (decode every frame).
        self._play_fps = file_fps if target_fps is None else float(target_fps)
        self.fps       = self._play_fps if self._play_fps > 0 else file_fps
        self._loop      = loop
        self._t0:        Optional[float] = None   # wall time of first delivered frame
        self._delivered  = 0                       # frames consumed (read + grabbed)
        self.device_name = f"video:{os.path.basename(path)}"
        _mode = ("unpaced (every frame, max speed)" if self._play_fps <= 0
                 else f"real time @ {self._play_fps:.0f}fps (drops frames to stay synced)")
        print(f"[Camera] DEV video source: {path!r} {self.width}x{self.height} "
              f"@ file {file_fps:.0f}fps -> {_mode}, loop={loop}")

    def _read_one(self) -> Tuple[bool, Optional[np.ndarray]]:
        ok, frame = self._cap.read()
        if not ok and self._loop and self._rewind():
            ok, frame = self._cap.read()
        if ok:
            self._delivered += 1
            return True, frame
        return False, None

    def _rewind(self) -> bool:
        self._cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
        self._t0 = None          # restart the real-time clock after wrapping
        self._delivered = 0
        return True

    def read(self) -> Tuple[bool, Optional[np.ndarray]]:
        import time as _time
        if self._play_fps <= 0:                    # unpaced: decode every frame
            return self._read_one()

        now = _time.monotonic()
        if self._t0 is None:
            self._t0 = now
        scheduled = self._t0 + self._delivered / self._play_fps
        if now < scheduled:
            _time.sleep(scheduled - now)           # ahead of schedule: wait
        else:                                      # behind: drop the missed frames
            behind = int((now - scheduled) * self._play_fps)
            for _ in range(behind):
                if not self._cap.grab():           # EOF mid-skip -> let _read_one wrap
                    break
                self._delivered += 1
        return self._read_one()

    def waitKey(self, delay: int = 1) -> int:
        return cv2.waitKey(delay)

    def release(self) -> None:
        self._cap.release()


# ── Factory ───────────────────────────────────────────────────────────────────

def build_camera_source(
    device_name: Optional[str] = None,
) -> "FfmpegCameraSource | VideoCaptureSource":
    """
    Auto-select camera backend, using whatever resolution/framerate the device delivers.
      1. If *device_name* is given, use that device (HDR or SDR as appropriate).
      2. Otherwise probe DirectShow devices for P010 (HDR) capability.
      3. If found → FfmpegCameraSource (stable HDR conversion via ffmpeg).
      4. Otherwise → VideoCaptureSource on OBS Virtual Camera (SDR fallback).
    """
    if device_name:
        print(f"[Camera] Using configured device: {device_name!r}")
        if _device_has_p010(device_name):
            return FfmpegCameraSource(device_name)
        devices = list_dshow_video_devices()
        idx = next((i for i, n in enumerate(devices) if n == device_name), 0)
        return VideoCaptureSource(idx, device_name=device_name)

    print("[Camera] Probing DirectShow devices for P010 (HDR)...")
    p010_device = _find_p010_device()
    if p010_device:
        print(f"[Camera] P010 device found: {p010_device!r} - using ffmpeg HDR path")
        return FfmpegCameraSource(p010_device)

    print("[Camera] No P010 device - falling back to SDR (cv2.VideoCapture)")
    obs_idx, obs_name = _find_obs_device()
    return VideoCaptureSource(obs_idx, device_name=obs_name)
