"""
Camera source abstraction supporting HDR (ffmpeg pipe) and SDR (cv2.VideoCapture).

Auto-detection logic (build_camera_source):
  1. Query DirectShow devices for P010 (10-bit HDR) capability via ffmpeg.
  2. If found → FfmpegCameraSource: ffmpeg captures P010, converts to bgr24 in
     the ffmpeg process, pipes raw bytes to Python.  A daemon reader thread pumps
     frames at 60 fps; .read() blocks until the next frame arrives, matching the
     cv2.VideoCapture.read() contract exactly.
  3. Otherwise → VideoCaptureSource: thin cv2.VideoCapture wrapper (SDR path,
     used for OBS Virtual Camera and other SDR sources).

Why bgr24 via ffmpeg rather than keeping P010 in Python:
  - Templates are generated by the program itself from the same frames it
    captures, so the absolute pixel values don't matter — only consistency.
  - ffmpeg's BT.2020 → bgr24 conversion is stable frame-to-frame; the Elgato
    driver's internal HDR→SDR conversion is not, causing minimap circle tracking
    to fail on HDR content.
  - All existing OpenCV code (template matching, Hough, HSV) works unchanged
    because frames arrive as standard uint8 BGR.
"""

import ctypes
import ctypes.wintypes
import msvcrt
import subprocess
import threading
from typing import Optional, Tuple

import cv2
import numpy as np


# ── Internal helpers ──────────────────────────────────────────────────────────

def _run(*args, **kwargs):
    return subprocess.run(*args, capture_output=True, text=True, **kwargs)


# Windows PeekNamedPipe: returns how many bytes are immediately available in
# the OS pipe buffer without consuming them.  Used to detect frame backlog.
_kernel32 = ctypes.windll.kernel32
_kernel32.PeekNamedPipe.argtypes = [
    ctypes.wintypes.HANDLE,
    ctypes.c_void_p, ctypes.wintypes.DWORD, ctypes.c_void_p,
    ctypes.POINTER(ctypes.wintypes.DWORD),
    ctypes.c_void_p,
]
_kernel32.PeekNamedPipe.restype = ctypes.wintypes.BOOL


def _available_bytes(win_handle: int) -> int:
    avail = ctypes.wintypes.DWORD(0)
    _kernel32.PeekNamedPipe(win_handle, None, 0, None, ctypes.byref(avail), None)
    return avail.value


def _fill_frame(raw_io, mv: memoryview, n: int) -> bool:
    """Fill memoryview mv[:n] from raw (unbuffered) FileIO. Returns False on EOF."""
    total = 0
    while total < n:
        got = raw_io.readinto(mv[total:])
        if not got:
            return False
        total += got
    return True


# ── Device discovery ──────────────────────────────────────────────────────────

def list_dshow_video_devices() -> list[str]:
    """Return friendly names of all DirectShow video devices via ffmpeg."""
    r = _run(["ffmpeg", "-f", "dshow", "-list_devices", "true", "-i", "dummy"])
    names = []
    for line in r.stderr.splitlines():
        if "(video)" in line and '"' in line:
            names.append(line.split('"')[1])
    return names


def _device_has_p010(device_name: str) -> bool:
    """Return True if the device advertises the P010 FourCC (10-bit HDR) via dshow."""
    r = _run(["ffmpeg", "-f", "dshow", "-list_options", "true",
              "-i", f"video={device_name}"])
    return "0x30313050" in r.stderr   # P010 little-endian FourCC


def _find_p010_device() -> Optional[str]:
    """Return the first DirectShow device that advertises P010, or None."""
    for name in list_dshow_video_devices():
        if _device_has_p010(name):
            return name
    return None


def _find_obs_index() -> int:
    """Return the cv2.VideoCapture index for OBS Virtual Camera, or 0."""
    for index, name in enumerate(list_dshow_video_devices()):
        if "obs" in name.lower():
            print(f"[Camera] OBS Virtual Camera at index {index}: {name!r}")
            return index
    return 0


# ── Source classes ────────────────────────────────────────────────────────────

class FfmpegCameraSource:
    """
    HDR camera source: ffmpeg dshow → bgr24 pipe.

    Replicates cv2.VideoCapture's "always return the latest frame" behaviour:
    a daemon reader thread fills frames via raw (unbuffered) FileIO, then uses
    PeekNamedPipe to detect any queued backlog and drains it by overwriting the
    same buffer — only the newest frame is ever delivered to the main loop.

    Three pre-allocated numpy buffers rotate in a ring so the reader and main
    loop always work on different memory with no per-frame allocation.
    """

    def __init__(self, device_name: str, width: int = 1920, height: int = 1080,
                 fps: int = 60) -> None:
        self.width  = width
        self.height = height
        self.fps    = fps
        self._n = width * height * 3  # bytes per bgr24 frame
        self._pending_key = -1        # key press captured while waiting for a frame

        # Triple-buffer ring: reader writes to bufs[_wi]; .read() returns
        # bufs[(_wi + 2) % 3] (the frame written just before the current one).
        # With three slots the reader is always at least one buffer ahead of
        # the main loop, so they never share memory.
        self._bufs = [np.empty((height, width, 3), dtype=np.uint8)
                      for _ in range(3)]
        self._wi        = 0
        self._lock      = threading.Lock()
        self._new_frame = threading.Event()
        self._running   = True

        # Pre-allocated drain buffer: holds up to 16 frames for batch skipping.
        # A single large readinto drains all queued frames in one OS call instead
        # of one readinto-loop per frame, cutting drain time from O(frames × 15ms)
        # to ~1–2ms regardless of backlog size.
        _DRAIN_FRAMES   = 16
        self._drain_buf = np.empty(self._n * _DRAIN_FRAMES, dtype=np.uint8)
        self._drain_mv  = memoryview(self._drain_buf)

        cmd = [
            "ffmpeg",
            "-fflags",           "nobuffer",
            "-flags",            "low_delay",
            "-loglevel",         "error",
            "-f", "dshow",
            "-rtbufsize",        "16M",        # ~4 P010 frames; 1M was sub-frame, causing drops
            "-thread_queue_size", "1",          # restrict ffmpeg's input thread queue to 1 packet
            "-video_size", f"{width}x{height}", "-framerate", str(fps),
            "-i", f"video={device_name}",
            "-f", "rawvideo", "-pix_fmt", "bgr24", "pipe:1",
        ]
        self._proc = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
        )
        self._thread = threading.Thread(
            target=self._reader, daemon=True, name="CameraReader",
        )
        self._thread.start()
        print(f"[Camera] ffmpeg HDR pipe: {device_name!r} "
              f"{width}x{height} @ {fps}fps (bgr24)")

    def _reader(self) -> None:
        import time as _time
        raw    = self._proc.stdout.raw          # unbuffered FileIO — no internal copy
        handle = msvcrt.get_osfhandle(raw.fileno())
        n      = self._n

        _diag_t     = _time.monotonic()
        _diag_total = 0      # frames delivered to ring
        _diag_drain = 0      # frames discarded in drain
        _DIAG_INTERVAL = 5.0

        while self._running:
            wb = self._bufs[self._wi]
            mv = memoryview(wb.ravel())

            # Fill one complete frame directly into the pre-allocated buffer.
            t0 = _time.monotonic()
            if not _fill_frame(raw, mv, n):
                self._running = False
                break
            fill_ms = (_time.monotonic() - t0) * 1000

            # Drain any backlogged frames in one large batch read.
            # Reading all queued bytes in a single readinto call is ~10× faster
            # than draining one frame at a time; the OS hands back all buffered
            # data in one shot since it's already in kernel memory.
            avail = _available_bytes(handle)
            drained = 0
            if avail >= n:
                drain_mv = self._drain_mv
                to_read  = min((avail // n) * n, len(drain_mv))
                total    = 0
                while total < to_read:
                    got = raw.readinto(drain_mv[total:to_read])
                    if not got:
                        self._running = False
                        return
                    total += got
                complete = total // n
                if complete > 0:
                    last = (complete - 1) * n
                    mv[:] = drain_mv[last : last + n]
                    drained = complete

            # Advance the ring and signal the main loop.
            with self._lock:
                self._wi = (self._wi + 1) % 3
            self._new_frame.set()

            _diag_total += 1
            _diag_drain += drained

            now = _time.monotonic()
            if now - _diag_t >= _DIAG_INTERVAL:
                elapsed = now - _diag_t
                fps_in  = (_diag_total + _diag_drain) / elapsed
                fps_out = _diag_total / elapsed
                print(
                    f"[Camera] reader: fill={fill_ms:.1f}ms  "
                    f"in={fps_in:.1f}fps  out={fps_out:.1f}fps  "
                    f"drain={_diag_drain} frames in {elapsed:.0f}s  "
                    f"pipe_avail={avail/n:.1f}fr"
                )
                _diag_t     = now
                _diag_total = 0
                _diag_drain = 0

    def read(self) -> Tuple[bool, Optional[np.ndarray]]:
        # Wait for the next frame while keeping the Windows message pump alive.
        #
        # cv2.waitKey(1) was the original approach but is the wrong tool here:
        # it's designed to be called once after imshow, not 16× per frame.
        # More importantly, it sleeps via the Windows timer which defaults to
        # 15.6ms resolution — making every "1ms" wait wildly variable.
        #
        # Instead: cv2.pollKey() processes all pending messages immediately
        # (non-blocking), then Event.wait(0.001) sleeps precisely 1ms thanks
        # to timeBeginPeriod(1) set in main.py. This gives the same message-pump
        # coverage as waitKey while being far more predictable.
        import time as _time
        deadline = _time.monotonic() + 5.0
        while True:
            k = cv2.pollKey()   # non-blocking: flush Windows message queue now
            if k != -1:
                self._pending_key = k
            if self._new_frame.wait(0.001):   # sleeps ≤1ms; precise with timeBeginPeriod(1)
                break
            if _time.monotonic() > deadline:
                return False, None
        self._new_frame.clear()
        with self._lock:
            # The slot written two steps ago is safe: the reader is now one
            # full slot ahead, and the main loop processes in under a frame period.
            return True, self._bufs[(self._wi + 2) % 3]

    def waitKey(self, delay: int = 1) -> int:
        """Return any key press captured during read(), then fall back to cv2.waitKey()."""
        k = self._pending_key
        self._pending_key = -1
        if k != -1:
            return k
        return cv2.waitKey(delay)

    def release(self) -> None:
        self._running = False
        self._proc.terminate()
        try:
            self._proc.wait(timeout=3.0)
        except subprocess.TimeoutExpired:
            self._proc.kill()


class VideoCaptureSource:
    """SDR camera source: thin wrapper around cv2.VideoCapture (dshow backend)."""

    def __init__(self, index: int, width: int = 1920, height: int = 1080,
                 fps: int = 60) -> None:
        self._cap = cv2.VideoCapture(index, cv2.CAP_DSHOW)
        self._cap.set(cv2.CAP_PROP_FRAME_WIDTH,  width)
        self._cap.set(cv2.CAP_PROP_FRAME_HEIGHT, height)
        self._cap.set(cv2.CAP_PROP_FPS,          fps)
        self.width  = int(self._cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        self.height = int(self._cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        self.fps    = self._cap.get(cv2.CAP_PROP_FPS)
        print(f"[Camera] DSHOW SDR: index={index} "
              f"{self.width}x{self.height} @ {self.fps}fps")

    def read(self) -> Tuple[bool, Optional[np.ndarray]]:
        return self._cap.read()

    def waitKey(self, delay: int = 1) -> int:
        return cv2.waitKey(delay)

    def release(self) -> None:
        self._cap.release()


# ── Factory ───────────────────────────────────────────────────────────────────

def build_camera_source(
    width: int = 1920,
    height: int = 1080,
    fps: int = 60,
) -> "FfmpegCameraSource | VideoCaptureSource":
    """
    Auto-select camera backend:
      1. Probe DirectShow devices for P010 (HDR) capability.
      2. If found → FfmpegCameraSource (stable HDR conversion via ffmpeg).
      3. Otherwise → VideoCaptureSource on OBS Virtual Camera (SDR fallback).
    """
    print("[Camera] Probing DirectShow devices for P010 (HDR)...")
    p010_device = _find_p010_device()
    if p010_device:
        print(f"[Camera] P010 device found: {p010_device!r} — using ffmpeg HDR path")
        return FfmpegCameraSource(p010_device, width, height, fps)

    print("[Camera] No P010 device — falling back to SDR (cv2.VideoCapture)")
    return VideoCaptureSource(_find_obs_index(), width, height, fps)
